name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Verify Docker Hub Login
       run: docker info
      - name: List directory structure
        run: |
          ls -R
          echo "Backend directory:"
          ls -la ./backend
          echo "Frontend directory:"
          ls -la ./frontend
      - name: Build and push backend Docker image
        working-directory: ./backend
        run: |
          docker build -f ./backend/Dockerfile -t halludbam/backend:latest ./backend
          docker push halludbam/backend:latest

      - name: Build and push frontend Docker image
        working-directory: ./frontend
        run: |
          docker build -f ./frontend/Dockerfile -t halludbam/frontend:latest ./frontend
          docker push halludbam/frontend:latest

